//# Get revision info; generated by CMake/makeversion

//## pkg=Common
//## incpath=Common
//## incdir=include/Common

#include <Common/Package__Version.h>
#include <Common/Version.h>
#include "FillPackage__VersionInc.h"

namespace LOFAR {
  Version CommonVersion::getInfo()
  {
    return Version ("Common",
		    getVersion(), getConfVersion(),
		    getRevision(), getPackageRevision(),
		    getNrChangedFiles(),
		    getBuildTime(), getBuildUser(), getBuildMachine());
  }

  std::string CommonVersion::getVersion()
    { return "trunk"; }
  std::string CommonVersion::getConfVersion()
    { return "3.1"; }
  std::string CommonVersion::getRevision()
    { return "14031"; }
  std::string CommonVersion::getPackageRevision()
    { return "13938"; }
  std::string CommonVersion::getNrChangedFiles()
    { return "0"; }
}

//# FillPackage__VersionFunc.h is generated in the build area by
//# LofarPackageVersion.cmake. It contains function fillInfo.
#include "FillPackage__VersionFunc.h"
