//# Print revision info; generated by CMake/makeversion

#include <MS/Package__Version.h>
#include <Common/Version.h>
#include <iostream>

using namespace LOFAR;

int main (int argc, const char* argv[])
{
  std::string type = "brief";
  if (argc > 1) {
    type = argv[1];
  }
  Version::show<MSVersion> (std::cout, "MS", type);
  return 0;
}
