name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build on Ubuntu 20.04
      run: docker build . --file .ci/ubuntu.20.04.docker --tag makems2004:$(date +%s)
    - name: Build on Ubuntu 22.04
      run: docker build . --file .ci/ubuntu.22.04.docker --tag makems2204:$(date +%s)
